[package]
name = "brain_fudge"
version = "0.1.0"
authors = ["Mark Ghebrial"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Ha, no dependencies!